services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app 
    ports:
      - 8000:8000
    env_file:
      - ./backend/env/.env.dev
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
       TIPTAP_PRO_TOKEN: TOKEN
    # volumes:
    #   - ./frontend:/app
    ports:
      - 3000:3000
    env_file:
      - ./frontend/.env.dev
