services:
  finpanel-backend-fastapi:
   build:
     context: ./backend
     dockerfile: Dockerfile
   volumes:
    - ./backend:/app 
   ports:
    - "127.0.0.1:8000:8000"
   env_file:
    - ./backend/.env.dev