import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import 'cal-sans';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full font-sans">
      <body className={`${inter.className} h-full flex flex-col`}>
        <main className="h-full">{children}</main>
      </body>
    </html>
  );
}
