create extension if not exists "vector" with schema "extensions";


create table "public"."placeholder" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."placeholder" enable row level security;

CREATE UNIQUE INDEX placeholder_pkey ON public.placeholder USING btree (id);

alter table "public"."placeholder" add constraint "placeholder_pkey" PRIMARY KEY using index "placeholder_pkey";

grant delete on table "public"."placeholder" to "anon";

grant insert on table "public"."placeholder" to "anon";

grant references on table "public"."placeholder" to "anon";

grant select on table "public"."placeholder" to "anon";

grant trigger on table "public"."placeholder" to "anon";

grant truncate on table "public"."placeholder" to "anon";

grant update on table "public"."placeholder" to "anon";

grant delete on table "public"."placeholder" to "authenticated";

grant insert on table "public"."placeholder" to "authenticated";

grant references on table "public"."placeholder" to "authenticated";

grant select on table "public"."placeholder" to "authenticated";

grant trigger on table "public"."placeholder" to "authenticated";

grant truncate on table "public"."placeholder" to "authenticated";

grant update on table "public"."placeholder" to "authenticated";

grant delete on table "public"."placeholder" to "service_role";

grant insert on table "public"."placeholder" to "service_role";

grant references on table "public"."placeholder" to "service_role";

grant select on table "public"."placeholder" to "service_role";

grant trigger on table "public"."placeholder" to "service_role";

grant truncate on table "public"."placeholder" to "service_role";

grant update on table "public"."placeholder" to "service_role";


